linuxdeepin/deepin-update-ui

debian/postinst
Force cache refresh after installation to avoid the problem of cache not being updated in a timely manner
pms TASK-368711
=> feat: Clear QML cache after installation

src/dcc-update-plugin/operation/updatemodel.cpp, src/dcc-update-plugin/operation/updatemodel.h, src/dcc-update-plugin/operation/updatework.cpp, src/dcc-update-plugin/operation/updatework.h, src/dcc-update-plugin/qml/UpdateList.qml, src/dcc-update-plugin/qml/updateMain.qml
1. Added privacyAgreementText() method to UpdateModel for localized privacy policy links
2. Implemented openUrl() helper method in UpdateWorker for URL handling
3. Reorganized update status pages with proper weighting and visibility logic
4. Added new privacy agreement display component in QML
5. Fixed download state handling by setting showCheckUpdate flag
feat: 增加更新模块的隐私协议和UI改进
1. 在UpdateModel中添加privacyAgreementText()方法用于本地化隐私政策链接
2. 在UpdateWorker中实现openUrl()辅助方法处理URL
3. 重新组织更新状态页面，优化权重和显示逻辑
4. 在QML中添加新的隐私协议显示组件
5. 通过设置showCheckUpdate标志修复下载状态处理
pms: Bug-314999
pms: Bug-314943
pms: Bug-314673
pms: Bug-313865
=> feat: add update module with privacy agreement and UI improvements

src/dcc-update-plugin/operation/updatelistmodel.cpp, src/dcc-update-plugin/operation/updatelistmodel.h, src/dcc-update-plugin/operation/updatemodel.cpp, src/dcc-update-plugin/operation/updatemodel.h, src/dcc-update-plugin/operation/updatework.cpp, src/dcc-update-plugin/operation/updatework.h, src/dcc-update-plugin/qml/UpdateControl.qml, src/dcc-update-plugin/qml/UpdateList.qml, src/dcc-update-plugin/qml/updateMain.qml
1. There will be no blank pages after the backup is completed
2. During the installation process, other uninstalled lists cannot be clicked on
3. Open the update settings option
pms: Bug-313751
pms: Bug-314671
=> fix: installation status optimization

src/dcc-update-plugin/qml/UpdateSetting.qml, src/dcc-update-plugin/qml/updateMain.qml
1. Added battery level check (60% threshold) to enable/disable update controls
2. Added updateModeDisabled check to disable settings when updates are not allowed
3. Improved error messages to show battery warning when level is low
4. Consolidated enable/disable logic across multiple update controls
These changes ensure:
- Updates are blocked when battery is too low (preventing potential issues)
- Settings are properly disabled when update mode is restricted
- Users get clear feedback about battery requirements
- Consistent behavior across different update failure scenarios
fix: 更新控制改进电池和禁用状态处理
1. 添加电池电量检查（60%阈值）来控制更新控件的启用/禁用
2. 添加updateModeDisabled检查以在更新不允许时禁用设置
3. 改进错误消息，在电量低时显示电池警告
4. 统一多个更新控件的启用/禁用逻辑
这些更改确保：
- 电池电量过低时阻止更新（防止潜在问题）
- 更新模式受限时正确禁用设置
- 用户能清楚了解电池电量要求
- 不同更新失败场景下行为一致
=> fix: update control improvements for battery and disabled states

src/dcc-update-plugin/operation/updatework.cpp
Remove redundant `IsCommunitySystem` condition and standardize the third-party update check to rely solely on `DConfigWatcher` for consistency across the codebase. This ensures uniform behavior regardless of the system type.
log: as title
pms: BUG-316683
=> fix: The switch updated by third-party sources has been reset

src/dcc-update-plugin/operation/updatemodel.cpp
1. Restructured privacy policy URL generation to handle community and commercial versions separately
2. Simplified URL construction by removing region suffix for community version
3. Added direct Chinese/English URLs for community version (deepin.org)
4. Maintained existing region-based URLs for commercial version (uniontech.com)
5. Improved code readability by removing redundant static lists and simplifying conditionals
The changes ensure proper privacy policy links are generated for different system types and regions, while making the code more maintainable and consistent with the actual privacy policy documentation locations.
fix: 更新隐私政策URL处理逻辑
1. 重构隐私政策URL生成逻辑，区分社区版和商业版处理
2. 简化社区版URL构造，不再使用区域后缀
3. 为社区版添加直接的中文/英文URL（deepin.org）
4. 商业版保持原有的基于区域的URL（uniontech.com）
5. …
=> fix: update privacy policy URL handling logic

src/dcc-update-plugin/translations/update_lt.ts
=> fix: update translation

src/dcc-update-plugin/qml/update.qml, src/dcc-update-plugin/qml/updateMain.qml
1. Replaced hasHandledChildrenChange with more descriptive hasView property
2. Added Component.onDestruction handler to track view lifecycle
3. Consolidated update check logic in updateMain.qml with hasCheckUpdate flag
4. Improved comments explaining the purpose of each signal and property
5. Combined multiple Connections blocks into a single one for better organization
The changes improve the reliability of update checks by:
- Better tracking when the update view is active/inactive
- Preventing duplicate update checks
- Making the code more maintainable with clearer state management
- Handling edge cases when the module is accessed via DBus
fix: 改进更新模块状态管理
1. 用更具描述性的 hasView 属性替换了 hasHandledChildrenChange
2. 添加 Component.onDestruction 处理程序来跟踪视图生命周期
3. 在 updateMain.qml 中使用 hasCheckUpdate …
=> fix: improve update module state management

src/dcc-update-plugin/operation/updatemodel.cpp, src/dcc-update-plugin/operation/updatemodel.h, src/dcc-update-plugin/operation/updatework.cpp, src/dcc-update-plugin/operation/updatework.h, src/dcc-update-plugin/qml/UpdateSetting.qml
1. Changed time representation from minutes (int) to string format (HH:MM) in UpdateModel
2. Removed time conversion functions in UpdateWorker since no longer needed
3. Updated QML to use new DccTimeRange component instead of SpinBox
4. Added immediate model update before DBus call to improve UI responsiveness
The changes simplify time handling by using string format directly instead of converting between minutes and time strings. This makes the code more straightforward and removes unnecessary conversion logic. The immediate model update before DBus call improves user experience by making UI changes appear instantly.
fix: 使用 DccTimeRange 组件替代 SpinBox
1. 在 UpdateModel 中将时间表示从分钟数(int)改为字符串格式(HH:MM)
2. 移除了 UpdateWorker 中不再需要的时间转换函数
3. 更新 QML 使用新的 DccTimeRange 组件替代 SpinBox
4. 在 DBus …
=> fix: use DccTimeRange component instead of SpinBox

src/dcc-update-plugin/qml/UpdateSetting.qml
Added clearButton.active property to show clear button only when input is focused and contains text
fix: 在下载速度限制输入中启用清除按钮
添加 clearButton.active 属性，仅在输入框获得焦点且包含文本时显示清除
按钮
=> fix: enable clear button in download speed limit input

src/dde-abrecovery/recoverydialog.cpp, src/dde-update/updateworker.cpp
1. Changed config paths from "org.deepin.lastore" to "org.deepin.dde.lastore" in both recoverydialog.cpp and updateworker.cpp
2. Updated corresponding log messages to reflect new namespace
3. This change aligns with the new DDE namespace convention for consistency across the project
fix: 更新lastore配置路径到新的dde命名空间
1. 在recoverydialog.cpp和updateworker.cpp中将配置路径 从"org.deepin.lastore"改为"org.deepin.dde.lastore"
2. 更新了相应的日志消息以反映新的命名空间
3. 此更改符合项目新的DDE命名空间约定，保持一致性
pms: BUG-313665
=> fix: update lastore config paths to new dde namespace

CMakeLists.txt, src/dcc-update-plugin/qml/UpdateControl.qml, src/dcc-update-plugin/qml/UpdateList.qml
1. Removed es_MX from translation languages list as it's redundant (es covers Mexican Spanish)
2. Reduced progress bar width from 240 to 210 in UpdateControl.qml for better visual balance
3. Adjusted left/right padding in UpdateList.qml (10->6 left, 10->12 right) to improve item spacing
4. These changes improve UI consistency and remove unnecessary translation redundancy
fix: 调整UI布局和翻译设置
1. 从翻译语言列表中移除es_MX（西班牙语已包含墨西哥西班牙语）
2. 将UpdateControl.qml中的进度条宽度从240减少到210以获得更好的视觉平衡
3. 调整UpdateList.qml中的左右边距（左10->6，右10->12）以改善项目间距
4. 这些更改提高了UI一致性并移除了不必要的翻译冗余
pms: Bug-321647
=> fix: adjust UI layout and translation settings

src/dcc-update-plugin/qml/UpdateControl.qml, src/dcc-update-plugin/qml/UpdateList.qml, src/dcc-update-plugin/qml/updateMain.qml
1. Added updateListcheck property to control check icon visibility in UpdateControl
2. Reduced initAnimation dimensions from 32x32 to 24x24 for better UI proportion
3. Modified update title to show "Downloading updates..." during download state
4. Disabled check icons in success dialog by setting updateListcheck to false
5. Connected checkIconVisible property between UpdateControl and UpdateList components
fix: 更新控制和列表可见性改进
1. 添加updateListcheck属性控制UpdateControl中的勾选图标可见性
2. 将initAnimation尺寸从32x32减小到24x24以获得更好的UI比例
3. 修改更新标题在下载状态时显示"正在下载更新..."
4. 通过设置updateListcheck为false在成功对话框中禁用勾选图标
5. 在UpdateControl和UpdateList组件之间连接checkIconVisible属性
pms: bug-321597
=> fix: update control and list visibility improvements

src/dcc-update-plugin/qml/UpdateSelectDialog.qml
1. Added keyboard navigation between buttons using KeyNavigation properties
2. Implemented auto-focus on shutdownBtn when dialog becomes visible
3. Added unique ids to all buttons for better reference
4. Ensured circular navigation between all three buttons (silent, reboot, shutdown)
These changes improve accessibility by allowing keyboard-only users to navigate between options more efficiently. The auto-focus on the shutdown button provides a sensible default starting point for keyboard users.
feat: 改进更新对话框的键盘导航功能
1. 使用 KeyNavigation 属性添加按钮间的键盘导航
2. 实现对话框显示时自动聚焦到 shutdownBtn
3. 为所有按钮添加唯一ID以便引用
4. 确保三个按钮(静默安装、重启更新、关机更新)之间可循环导航
这些改进提升了可访问性，使仅使用键盘的用户能更高效地在选项间导航。自动聚
焦到关机按钮为键盘用户提供了合理的默认起始点。
pms: BUG-319237
=> feat: improve keyboard navigation in update dialog

.reuse/dep5, debian/control, src/common/common/logwatcherhelper.cpp, src/common/common/logwatcherhelper.h, src/common/dbus/updatedbusproxy.cpp, src/common/dbus/updatedbusproxy.h, src/dcc-update-plugin/operation/updatework.cpp, src/dde-update/CMakeLists.txt, src/dde-update/misc/52-deepin-update-ui.rules, src/dde-update/misc/copy-update-log.sh, src/dde-update/misc/deepin-update-log-copy@.service, src/dde-update/updateworker.cpp
1. Replace file system watcher with DBus-based log monitoring
2. Implement pipe-based log data transfer for better security
3. Add historical and realtime log fetching capabilities
4. Introduce systemd service for secure log file copying
5. Fix potential security issues with file permissions
1. 从文件系统监控改为基于DBus的日志监控
2. 实现基于管道的日志数据传输以提高安全性
3. 添加历史日志和实时日志获取功能
4. 引入systemd服务实现安全的日志文件复制
5. 修复文件权限相关的潜在安全问题
refactor: 迁移更新日志监控到DBus接口
1. 将文件系统监控替换为基于DBus的日志监控
2. 实现基于管道的日志数据传输以提高安全性
3. 添加历史日志和实时日志获取功能
4. 引入systemd服务实现安全的日志文件复制
5. 修复文件权限相关的潜在安全问题
=> refactor: migrate update log monitoring to DBus interface

src/dde-update/updatewidget.cpp
1. Added m_contentWidget->adjustSize() call after collapseLogWidget() in showSuccessFrame()
2. This ensures proper widget resizing when the log section collapses
3. Prevents potential layout issues or empty spaces after update completion
fix: 更新完成后调整控件大小
1. 在showSuccessFrame()中的collapseLogWidget()后添加了 m_contentWidget->adjustSize()调用
2. 确保当日志部分折叠时正确调整控件大小
3. 防止更新完成后可能出现的布局问题或空白区域
PMS: BUG-321487 PMS: BUG-324587
=> fix: adjust widget size after update completion

src/dcc-update-plugin/qml/UpdateSetting.qml
Added a tooltip that appears when the checkbox text is truncated and hovered over. The tooltip shows the full text of the checkbox with a delay of 500ms and disappears after 3000ms. Also adjusted the layout to fill available width.
This change improves usability by ensuring users can always read the full checkbox label even when it's truncated due to space constraints. The tooltip only appears when needed (when text is truncated) and provides a smooth user experience with appropriate timing.
Log: Added tooltip for truncated checkbox text in update settings
Influence:
1. Test checkbox behavior with long text that gets truncated
2. Verify tooltip appears only when text is truncated
3. Test hover behavior and tooltip positioning
fix: 为截断的复选框文本添加提示工具
当复选框文本因空间不足被截断且鼠标悬停时，添加显示完整文本的提示工具。工 …
=> fix: add tooltip for truncated checkbox text

src/dcc-update-plugin/qml/CheckUpdate.qml, src/dcc-update-plugin/qml/UpdateControl.qml, src/dcc-update-plugin/qml/UpdateDisable.qml, src/dcc-update-plugin/qml/UpdateLogDialog.qml, src/dcc-update-plugin/qml/UpdateSetting.qml
1. Replaced hardcoded font sizes with DTK font manager styles (t8, t10) for better consistency
2. Changed ActionButton to ToolButton for pause/stop controls to match design system
3. Improved UpdateLogDialog layout calculation to be dynamic based on window height
4. Removed redundant font size settings that were overriding DTK styles
5. Added proper spacing in button rows for better visual hierarchy
Log:
1. Updated font styles across update module for consistency
2. Changed button types in update controls
3. Improved dialog layout responsiveness
Influence:
1. Verify all text displays correctly with new font styles
2. Check button functionality in update controls remains unchanged
3. Test UpdateLogDialog resizing behavior
4. Validate layout in different screen sizes
5. Confirm numeric …
=> fix: improve UI consistency and layout in update module

src/common/dbus/updatedbusproxy.cpp, src/common/dbus/updatedbusproxy.h, src/dcc-update-plugin/operation/updatework.cpp, src/dde-abrecovery/recoverydialog.cpp, src/dde-update/updateworker.cpp
1. Changed GetCheckIntervalAndTime to return QString instead of using output parameter
2. Fixed DBus call watcher lambdas to properly handle replies using watcher->reply()
3. Added error handling for empty check time return values
4. Ensured proper resource cleanup with watcher->deleteLater() in all cases
refactor: 改进 DBus 调用处理和返回值
1. 将 GetCheckIntervalAndTime 改为返回 QString 而不是使用输出参数
2. 修复 DBus 调用观察器的 lambda 函数，正确使用 watcher->reply() 处理 回复
3. 为空的检查时间返回值添加错误处理
4. 确保在所有情况下都正确使用 watcher->deleteLater() 进行资源清理
=> refactor: improve DBus call handling and return values

src/dde-update/fullscreenbackground.cpp, src/dde-update/updatewidget.cpp
1. Removed debug logging for content setting in FullScreenBackground to reduce noise
2. Changed log text color from solid white to 70% opacity white for better readability
3. Set minimum width for export button to ensure proper layout spacing
4. Added adjustSize() call for content widget to fix layout issues after error display
fix: 优化UI元素并移除调试日志
1. 移除FullScreenBackground中内容设置的调试日志以减少输出噪音
2. 将日志文本颜色从纯白色改为70%不透明度的白色以提高可读性
3. 为导出按钮设置最小宽度以确保正确的布局间距
4. 添加内容widget的adjustSize()调用以修复错误显示后的布局问题
pms: BUG-327201
pms: BUG-327211
=> fix: optimize UI elements and remove debug logs

src/dcc-update-plugin/operation/updatework.cpp, src/dcc-update-plugin/operation/updatework.h
Removed asynchronous signal emission for system activation state changes to improve response time. Previously, systemActivationChanged signal was emitted with Qt::QueuedConnection which caused delays in UI updates. Now directly call m_model->setSystemActivation() method to synchronously update the model state.
The change eliminates the need for QtConcurrent::run in onLicenseStateChange() slot, simplifying the code and making activation state updates immediate instead of queued. This addresses the performance issue where system activation status refresh was too slow through asynchronous signals.
Log: Improved system activation status refresh speed
Influence:
1. Test system activation state changes in real-time
2. Verify UI updates immediately reflect activation status
3. Check that …
=> fix: optimize system activation state refresh
