linuxdeepin/deepin-update-ui

src/dcc-update-plugin/CMakeLists.txt
src/dcc-update-plugin/operation/updateinteraction.cpp
src/dcc-update-plugin/operation/updateiteminfo.h
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/utils.h

add cmake qml info
Log: add cmake qml info
pms: Task-367053

feat: add cmake qml info

---

src/dcc-update-plugin/CMakeLists.txt
src/dcc-update-plugin/operation/common.h
src/dcc-update-plugin/operation/updatedatastructs.h
src/dcc-update-plugin/operation/updateiteminfo.h
src/dcc-update-plugin/operation/updateloghelper.cpp
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/utils.h
src/dcc-update-plugin/qml/UpdateSetting.qml
src/dcc-update-plugin/updatemodule.cpp
src/dcc-update-plugin/updatemodule.h

The control center failed to load update.so
Log: Failure to load the dynamic library

fix: Failure to load the dynamic library

---

src/dcc-update-plugin/operation/updatedbusproxy.cpp
src/dcc-update-plugin/operation/updatelistmodel.cpp
src/dcc-update-plugin/operation/updatelistmodel.h
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/UpdateList.qml
src/dcc-update-plugin/qml/updateMain.qml

add install update moudel
Log: add install update moudel
pms: BUG-307923

feat: add install update moudel

---

debian/changelog
debian/control

release 1.0.1
Log: bump version to 1.0.1

chore: bump version to 1.0.1

---

CMakeLists.txt
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/NoActive.qml
src/dcc-update-plugin/qml/updateMain.qml

show the settings page
Log: show the settings page

fix: show the settings page

---

src/dcc-update-plugin/qml/updateMain.qml

update settings page show failed
Log: update settings page show failed

fix: update settings page show failed

---

src/dcc-update-plugin/operation/updateinteraction.cpp
src/dcc-update-plugin/operation/updateinteraction.h
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/NoActive.qml
src/dcc-update-plugin/qml/UpdateSetting.qml
src/dcc-update-plugin/qml/updateMain.qml

The system cannot be updated without activation
pms: BUG-312835

fix: system activation status

---

src/dcc-update-plugin/CMakeLists.txt
src/dcc-update-plugin/operation/dconfigwatcher.cpp
src/dcc-update-plugin/qml/UpdateSetting.qml

Install the dconfig configuration file.
pms: BUG-312901

fix: install the dconfig configuration file.

---

debian/changelog
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml
src/dcc-update-plugin/translations/update_az.ts
src/dcc-update-plugin/translations/update_bo.ts
src/dcc-update-plugin/translations/update_ca.ts
src/dcc-update-plugin/translations/update_en.ts
src/dcc-update-plugin/translations/update_en_US.ts
src/dcc-update-plugin/translations/update_es.ts
src/dcc-update-plugin/translations/update_fi.ts
src/dcc-update-plugin/translations/update_fr.ts
src/dcc-update-plugin/translations/update_hu.ts
src/dcc-update-plugin/translations/update_it.ts
src/dcc-update-plugin/translations/update_ja.ts
src/dcc-update-plugin/translations/update_ko.ts
src/dcc-update-plugin/translations/update_nb_NO.ts
src/dcc-update-plugin/translations/update_pl.ts
src/dcc-update-plugin/translations/update_pt_BR.ts
src/dcc-update-plugin/translations/update_ru.ts
src/dcc-update-plugin/translations/update_uk.ts
src/dcc-update-plugin/translations/update_zh_CN.ts
src/dcc-update-plugin/translations/update_zh_HK.ts
src/dcc-update-plugin/translations/update_zh_TW.ts
src/dde-update/main.cpp

feat: add update back up

---

src/dcc-update-plugin/operation/updatelistmodel.cpp
src/dcc-update-plugin/operation/updatelistmodel.h
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml

The download package size shows 0
pms: BUG-313173

fix: the download package size shows 0

---

debian/changelog
src/dde-abrecovery/CMakeLists.txt

chore: remove unnecessary dependencies

---

src/dcc-update-plugin/operation/dconfigwatcher.cpp
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml
src/dcc-update-plugin/translations/update_az.ts
src/dcc-update-plugin/translations/update_bo.ts
src/dcc-update-plugin/translations/update_ca.ts
src/dcc-update-plugin/translations/update_en.ts
src/dcc-update-plugin/translations/update_en_US.ts
src/dcc-update-plugin/translations/update_es.ts
src/dcc-update-plugin/translations/update_fi.ts
src/dcc-update-plugin/translations/update_fr.ts
src/dcc-update-plugin/translations/update_hu.ts
src/dcc-update-plugin/translations/update_it.ts
src/dcc-update-plugin/translations/update_ja.ts
src/dcc-update-plugin/translations/update_ko.ts
src/dcc-update-plugin/translations/update_nb_NO.ts
src/dcc-update-plugin/translations/update_pl.ts
src/dcc-update-plugin/translations/update_pt_BR.ts
src/dcc-update-plugin/translations/update_ru.ts
src/dcc-update-plugin/translations/update_uk.ts
src/dcc-update-plugin/translations/update_zh_CN.ts
src/dcc-update-plugin/translations/update_zh_HK.ts
src/dcc-update-plugin/translations/update_zh_TW.ts

update translations
Log: update translations

feat: update translations

---

src/dcc-update-plugin/operation/qrc/icons/warning.svg
src/dcc-update-plugin/operation/qrc/update.qrc
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/UpdateList.qml
src/dcc-update-plugin/qml/update.qml
src/dcc-update-plugin/qml/updateMain.qml

Optimize the code structure
Log: Optimize the code structure

feat: optimize the code structure

---

src/dde-abrecovery/misc/rollback_check.sh

qdbus may not be pre installed in the system
pms: TASK-368711

feat: use dbus-send instead of qdbus

---

src/dcc-update-plugin/qml/updateMain.qml

Block the update settings page
Log: block the update settings

feat: block the update settings

---

.reuse/dep5
CMakeLists.txt
LICENSES/LGPL-3.0-or-later.txt
src/dcc-update-plugin/CMakeLists.txt
src/dde-abrecovery/CMakeLists.txt
src/dde-update/CMakeLists.txt
src/dde-update/abstractfullbackgroundinterface.h

chore(license): Organizing licenses and copyrights

---

src/dcc-update-plugin/operation/updatelistmodel.cpp
src/dcc-update-plugin/operation/updatelistmodel.h
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/UpdateList.qml

The checkbox function is not implemented
pms: BUG-313349

fix: The checkbox doesn't respond when clicked

---

src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml

Disable the checkbox during the download process.
pms: BUG-313771

fix: do not check the box during the download process

---

debian/changelog

chore: bump version 1.0.5

---

src/dcc-update-plugin/operation/common.h
src/dcc-update-plugin/operation/updateinteraction.cpp
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/QuitTestingChannelDialog.qml
src/dcc-update-plugin/qml/UpdateHistoryDialog.qml
src/dcc-update-plugin/qml/UpdateSetting.qml

add testing channel setting
Log: testing channel

feat: add testing channel setting

---

src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml

Add logic to prevent automatic update check if last check was within 24 hours
pms: BUG-313139

fix: disable automatic update check within 24 hours

---

src/dcc-update-plugin/operation/updatework.cpp

Check for updates by default every 24 hours
pms: BUG-313139

fix: check for updates by default every 24 hours

---

src/dcc-update-plugin/operation/dconfigwatcher.cpp

1. Added QCoreApplication include for thread management
2. Modified lambda connection to explicitly capture this pointer and
config
3. Changed singleton implementation to use dynamic allocation with
proper thread affinity
4. Set parent to qApp to ensure proper cleanup
5. Fixed potential thread safety issues in singleton pattern
fix: 改进 DConfigWatcher 线程安全和连接
1. 添加 QCoreApplication 包含用于线程管理
2. 修改 lambda 连接以显式捕获 this 指针和 config
3. 将单例实现改为使用动态分配并设置正确线程亲和性
4. 设置父对象为 qApp 确保正确清理
5. 修复单例模式中潜在的线程安全问题

fix: improve DConfigWatcher thread safety and connection

---

src/dcc-update-plugin/qml/UpdateSetting.qml

add advanced settings section with expandable details in update settings
pms: BUG-312907

fix: Advanced settings default expansion

---

src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/qml/CheckUpdate.qml
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/updateMain.qml

Disable other buttons when downloading starts
pms: Bug-314683

fix: download status optimization

---

src/dde-abrecovery/recoverydialog.cpp
src/dde-abrecovery/recoverydialog.h

Retrieve backup time and version information from Lastore daemon
pms: BUG-313657

fix: Not displaying the version and time of the last backup

---

src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/qml/UpdateSetting.qml
src/dcc-update-plugin/qml/updateMain.qml

optimize the logic of disable and enable system updates
pms: Bug-315923
pms: Bug-315921
pms: Bug-313465

fix: optimize the logic of disable and enable system updates

---

src/dcc-update-plugin/qml/UpdateSetting.qml

Hide security updates
log: as title
pms: BUG-316661

fix:  security updates toggle for community systems is avaliable

---

src/dde-update/updateworker.cpp

1. Remove redundant code for backup status updates and ensure that the status is set correctly during the backup process.
2. When a backup fails, update the error log and status to reflect the reason for the backup failure.
3. Optimize the error analysis logic and return the corresponding error type based on the current state. These changes have improved the accuracy of state management and error handling during the backup process.
pms: BUG-319019

fix: Update backup status handling and error analysis logic

---

src/common/common/logwatcherhelper.cpp
src/common/common/logwatcherhelper.h
src/common/dbus/updatedbusproxy.cpp
src/common/dbus/updatedbusproxy.h
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatemodel.h
src/dcc-update-plugin/operation/updatework.cpp
src/dcc-update-plugin/operation/updatework.h
src/dcc-update-plugin/qml/UpdateControl.qml
src/dcc-update-plugin/qml/UpdateLogDialog.qml
src/dcc-update-plugin/qml/updateMain.qml

1. Added FileWatcherHelper class to monitor update log file changes in /tmp
2. Implemented incremental reading of log file to avoid loading entire content
3. Added log export functionality to desktop with timestamped filename
4. Created new UpdateLogDialog to display real-time update logs
5. Integrated log viewing button in update interface components
6. Added model properties to store and update log content
7. Implemented proper file monitoring with QFileSystemWatcher
8. Added error handling for file operations and DBus calls
feat: 添加更新日志监控和导出功能
1. 新增 FileWatcherHelper 类用于监控 /tmp 目录下的更新日志文件变化
2. 实现增量读取日志文件功能，避免加载全部内容
3. 添加日志导出到桌面功能，文件名包含时间戳
4. 创建新的 UpdateLogDialog 对话框显示实时更新日志
5. 在更新界面组件中集成日志查看按钮
6. 添加模型属性用于存储和更新日志内容
7. 使用 QFileSystemWatcher 实现正确的文件监控
8. 为文件操作和 DBus 调用添加错误处理
pms: …

feat: add update log monitoring and export functionality

---

debian/changelog

chore: bump version to 1.0.15

---

debian/changelog

chore: bump version to 1.0.19

---

debian/changelog

chore: bump version to 1.0.21

---

debian/changelog

chore: bump version to 1.0.22

---

debian/changelog

chore: bump version to 1.0.23

---

src/common/common/dconfig_helper.cpp
src/common/common/logwatcherhelper.cpp
src/common/dbus/updatedbusproxy.cpp
src/common/dbus/updatejobdbusproxy.cpp
src/common/global_util/public_func.cpp
src/dcc-update-plugin/operation/appupdateinfolist.cpp
src/dcc-update-plugin/operation/dconfigwatcher.cpp
src/dcc-update-plugin/operation/dconfigwatcher.h
src/dcc-update-plugin/operation/mirrorinfolist.cpp
src/dcc-update-plugin/operation/updatehistorymodel.cpp
src/dcc-update-plugin/operation/updateinteraction.cpp
src/dcc-update-plugin/operation/updateiteminfo.cpp
src/dcc-update-plugin/operation/updatelistmodel.cpp
src/dcc-update-plugin/operation/updateloghelper.cpp
src/dcc-update-plugin/operation/updatemodel.cpp
src/dcc-update-plugin/operation/updatestatus.cpp
src/dcc-update-plugin/operation/updatestatusdata.cpp
src/dcc-update-plugin/operation/updatework.cpp
src/dde-abrecovery/backgroundwidget.cpp
src/dde-abrecovery/main.cpp
src/dde-abrecovery/recoverydialog.cpp
src/dde-update/blurtransparentbutton.cpp
src/dde-update/checksystemwidget.cpp
src/dde-update/fullscreen.cpp
src/dde-update/fullscreenbackground.cpp
src/dde-update/fullscreenmanager.cpp
src/dde-update/main.cpp
src/dde-update/updatemodel.cpp
src/dde-update/updatewidget.cpp
src/dde-update/updateworker.cpp

Improve log coverage by adding logs to necessary functions and branches for easy debugging
Log:

feat: Improve log coverage

---

debian/changelog

chore: bump version to 1.0.25

---

debian/changelog

chore: bump version to 1.0.27

---

debian/changelog

chore: bump version to 1.0.29
